services:
  nest-typeorm-api:
    container_name: nest-typeorm-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      WATCHPACK_POLLING: 'true'
    depends_on:
      nest-typeorm-postgres:
        condition: service_healthy
    ports:
      - '7001:3000'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - nest-typeorm-network

  nest-typeorm-postgres:
    image: postgres:16
    container_name: nest-typeorm-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '7432:5432'
    volumes:
      - nest-typeorm-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - nest-typeorm-network

  nest-typeorm-redis:
    image: 'redis:latest'
    restart: unless-stopped
    container_name: nest-typeorm-redis
    ports:
      - '7379:6379'
    volumes:
      - nest-typeorm-redis-data:/data
    networks:
      - nest-typeorm-network

volumes:
  nest-typeorm-data:
  nest-typeorm-redis-data:

networks:
  nest-typeorm-network:
    name: nest-typeorm-network
